events {
	worker_connections 768;
}

error_log /home/z3545907/git/kagemori/server/nginx-conf/logs/error.log;
pid /home/z3545907/git/kagemori/server/nginx-conf/nginx.pid;

http {

	client_body_temp_path /home/z3545907/git/kagemori/server/nginx-conf/tmp/client_body;
	proxy_temp_path /home/z3545907/git/kagemori/server/nginx-conf/tmp/proxy;
	fastcgi_temp_path /home/z3545907/git/kagemori/server/nginx-conf/tmp/fastcgi;
	uwsgi_temp_path /home/z3545907/git/kagemori/server/nginx-conf/tmp/uwsgi;
	scgi_temp_path /home/z3545907/git/kagemori/server/nginx-conf/tmp/scgi;


	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

	default_type application/octet-stream;
	gzip on;

	upstream kageauth {
		server [::1]:3621;
	}

	server {
		listen 9097;
		listen [::]:9097;

		server_name _;
		proxy_intercept_errors on;
		access_log /home/z3545907/git/kagemori/server/nginx-conf/logs/access.log;

		location = / {
			return 302 /kagemori/mapi/uri/login;
		}

		location / {
			auth_request /kagemori_session;
			
			auth_request_set $kagemori_proxy_target $upstream_http_x_kage_nginx;

			#if ($kagemori_proxy_target = "") {
			#	return 302 /kagemori/mapi/uri/login;
			#}
		
			proxy_pass http://unix://$kagemori_proxy_target;
			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";

			error_page 401 = @error401;
			error_page 500 = @error500;
		}
		
		location @error401 {
			return 302 /kagemori/mapi/uri/login;
		}

		location @error500 {
			return 302 /kagemori/mapi/uri/login;
		}

		location /uapi {
			auth_request /kagemori_session;
			
			auth_request_set $kagemori_proxy_target $upstream_http_x_kage_forward;

			#if ($kagemori_proxy_target = "") {
			#	return 302 /kagemori/mapi/uri/login;
			#}
		
			proxy_pass http://unix://$kagemori_proxy_target;
			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	
		location /kagemori {
			proxy_pass http://[::1]:3621/;
		}

		location /kagemori_session {
			internal;

			proxy_pass http://[::1]:3621/mapi/session;
			proxy_pass_request_body off;
			proxy_set_header Content-Length "";
			proxy_set_header X-Original-URI $request_uri;
			proxy_set_header X-Original-Method $request_method;
		}
	}
}
