# TODO: This code fucking sucks man
def write_nginx_config(out_path="./nginx-conf/nginx.conf", portal_url="portal.cluster.edu", nginx_prefix="", upstream_kageauth="[::1]:3621", server_listen_port="9007"):
    with open(out_path, "w") as out_fp:
        out_fp.write(f" events {")
        out_fp.write(f" 	worker_connections 768;")
        out_fp.write(f" }")
        out_fp.write(f"")
        out_fp.write(f" error_log {nginx_prefix}/logs/error.log;")
        out_fp.write(f" pid {nginx_prefix}/nginx.pid;")
        out_fp.write(f" ")
        out_fp.write(f" http {")
        out_fp.write(f" ")
        out_fp.write(f" 	client_body_temp_path {nginx_prefix}/tmp/client_body;")
        out_fp.write(f" 	proxy_temp_path {nginx_prefix}/tmp/proxy;")
        out_fp.write(f" 	fastcgi_temp_path {nginx_prefix}/tmp/fastcgi;")
        out_fp.write(f" 	uwsgi_temp_path {nginx_prefix}/tmp/uwsgi;")
        out_fp.write(f" 	scgi_temp_path {nginx_prefix}/tmp/scgi;")
        out_fp.write(f" ")
        out_fp.write(f" ")
        out_fp.write(f" 	sendfile on;")
        out_fp.write(f" 	tcp_nopush on;")
        out_fp.write(f" 	types_hash_max_size 2048;")
        out_fp.write(f" ")
        out_fp.write(f" 	default_type application/octet-stream;")
        out_fp.write(f" 	gzip on;")
        out_fp.write(f" ")
        out_fp.write(f" 	upstream kageauth {")
        out_fp.write(f" 		server {upstream_kageauth};")
        out_fp.write(f" 	}")
        out_fp.write(f" ")
        out_fp.write(f" 	map $http_upgrade $connection_upgrade {")
        out_fp.write(f" 	    default upgrade;")
        out_fp.write(f" 	    '' close;")
        out_fp.write(f" 	}")
        out_fp.write(f" ")
        out_fp.write(f" 	server {")
        out_fp.write(f" 		listen {server_listen_port};")
        out_fp.write(f" 		listen [::]:{server_listen_port};")
        out_fp.write(f" ")
        out_fp.write(f" 		server_name {portal_url}; ")
        out_fp.write(f" 		proxy_intercept_errors on;")
        out_fp.write(f" 		port_in_redirect off;")
        out_fp.write(f" 		access_log {nginx_prefix}/logs/portal.access.log;")
        out_fp.write(f" ")
        out_fp.write(f" 		location = / {")
        out_fp.write(f" 			return 302 /kagemori/mapi/uri/login;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location / {")
        out_fp.write(f" 			auth_request /kagemori_session;")
        out_fp.write(f" ")
        out_fp.write(f" 			auth_request_set $kagemori_proxy_target $upstream_http_x_kage_nginx;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_pass http://unix://$kagemori_proxy_target;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_set_header Host $host;")
        out_fp.write(f" 			proxy_set_header X-Real-IP $remote_addr;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-Proto $scheme;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_http_version 1.1;")
        out_fp.write(f" 			proxy_set_header Upgrade $http_upgrade;")
        out_fp.write(f" 			proxy_set_header Connection \"upgrade\";")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;")
        out_fp.write(f" 			proxy_read_timeout 86400s;")
        out_fp.write(f" 			proxy_send_timeout 86400s;")
        out_fp.write(f" ")
        out_fp.write(f" ")
        out_fp.write(f" 			error_page 401 = @error401;")
        out_fp.write(f" 			error_page 500 = @error500;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location @error401 {")
        out_fp.write(f" 			return 302 /kagemori/mapi/uri/login;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location @error500 {")
        out_fp.write(f" 			return 302 /kagemori/mapi/uri/login;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location /uapi {")
        out_fp.write(f" 			auth_request /kagemori_session;")
        out_fp.write(f" ")
        out_fp.write(f" 			auth_request_set $kagemori_proxy_target $upstream_http_x_kage_forward;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_pass http://unix://$kagemori_proxy_target;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_set_header Host $host;")
        out_fp.write(f" 			proxy_set_header X-Real-IP $remote_addr;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-Proto $scheme;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location /kagemori {")
        out_fp.write(f" 			proxy_pass http://{upstream_kageauth}/;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location /kagemori_session {")
        out_fp.write(f" 			internal;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_pass http://{upstream_kageauth}/mapi/session;")
        out_fp.write(f" 			proxy_pass_request_body off;")
        out_fp.write(f" 			proxy_set_header Content-Length "";")
        out_fp.write(f" 			proxy_set_header X-Original-URI $request_uri;")
        out_fp.write(f" 			proxy_set_header X-Original-Method $request_method;")
        out_fp.write(f" 		}")
        out_fp.write(f" 	}")
        out_fp.write(f" 	server {")
        out_fp.write(f" 		listen {server_listen_poart} default_server;")
        out_fp.write(f" 		listen [::]:{server_listen_port} default_server;")
        out_fp.write(f" ")
        out_fp.write(f" 		server_name _;")
        out_fp.write(f" 		proxy_intercept_errors on;")
        out_fp.write(f" 		port_in_redirect off;")
        out_fp.write(f" 		access_log {nginx_prefix}/logs/access.log;")
        out_fp.write(f" ")
        out_fp.write(f" 		location / {")
        out_fp.write(f" 			auth_request /kagemori_session;")
        out_fp.write(f" ")
        out_fp.write(f" 			auth_request_set $kagemori_proxy_target $upstream_http_x_kage_nginx;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_pass http://unix://$kagemori_proxy_target;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_set_header Host $host;")
        out_fp.write(f" 			proxy_set_header X-Real-IP $remote_addr;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;")
        out_fp.write(f" 			proxy_set_header X-Forwarded-Proto $scheme;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_http_version 1.1;")
        out_fp.write(f" 			proxy_set_header Upgrade $http_upgrade;")
        out_fp.write(f" 			proxy_set_header Connection \"upgrade\";")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;")
        out_fp.write(f" 			proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;")
        out_fp.write(f" 			proxy_read_timeout 86400s;")
        out_fp.write(f" 			proxy_send_timeout 86400s;")
        out_fp.write(f" ")
        out_fp.write(f" ")
        out_fp.write(f" 			error_page 401 = @error401;")
        out_fp.write(f" 			error_page 500 = @error500;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location /kagemori {")
        out_fp.write(f" 			proxy_pass http://{upstream_kageauth}/;")
        out_fp.write(f" 		}")
        out_fp.write(f" ")
        out_fp.write(f" 		location /kagemori_session {")
        out_fp.write(f" 			internal;")
        out_fp.write(f" ")
        out_fp.write(f" 			proxy_pass http://{upsteam_kageauth}/mapi/session;")
        out_fp.write(f" 			proxy_pass_request_body off;")
        out_fp.write(f" 			proxy_set_header Content-Length "";")
        out_fp.write(f" 			proxy_set_header X-Original-URI $request_uri;")
        out_fp.write(f" 			proxy_set_header X-Original-Method $request_method;")
        out_fp.write(f" 		}")
        out_fp.write(f" 	}")
        out_fp.write(f" }")
